[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
leafx_curve = "DK4Bd9x8aSK2tWuCVbRk7EEhSfZLRXGhimPYz6NFXMJJ"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
