const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const SOLANA_CHAIN='solana:devnet',RPC_URL='https://api.devnet.solana.com',EXPLORER='https://explorer.solana.com';
const state={step:1,wallet:null,account:null,address:null,web3:null,spl:null,connection:null};
let walletRegistry=null,registryReady=false;
function toast(m){const t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),3200)}
function short(a){return a?`${a.slice(0,4)}…${a.slice(-4)}`:'—'}function sol(v){return Number(v).toFixed(4)}
async function loadSolana(){
 if(state.web3&&state.spl&&walletRegistry){renderWalletOptions();return}
 try{
  const [{Connection,PublicKey,Keypair,SystemProgram,Transaction},spl,std]=await Promise.all([import('https://esm.sh/@solana/web3.js@1.98.4'),import('https://esm.sh/@solana/spl-token@0.4.14'),import('https://esm.sh/@wallet-standard/app@1.1.0')]);
  state.web3={Connection,PublicKey,Keypair,SystemProgram,Transaction};state.spl=spl;walletRegistry=std.getWallets();state.connection=new Connection(RPC_URL,'confirmed');registryReady=true;
  if(walletRegistry?.on)walletRegistry.on('register',renderWalletOptions);renderWalletOptions();setTimeout(renderWalletOptions,500);setTimeout(renderWalletOptions,1500);
 }catch(e){console.error(e);renderWalletOptions()}
}
function standardWallets(){if(!walletRegistry)return[];try{return [...walletRegistry.get()].filter(w=>w.chains?.some(c=>c===SOLANA_CHAIN||c==='solana:mainnet')).filter((w,i,a)=>a.findIndex(x=>x.name===w.name)===i)}catch{return[]}}
function legacyWallets(){const out=[];const candidates=[['Phantom',window.phantom?.solana],['Solflare',window.solflare],['Backpack',window.backpack?.solana],['Brave Wallet',window.braveSolana],['Coinbase Wallet',window.coinbaseSolana]];for(const [name,p] of candidates)if(p&&!out.some(x=>x.provider===p))out.push({name,provider:p,legacy:true});return out}
function allWallets(){const a=standardWallets(),names=new Set(a.map(w=>w.name));for(const x of legacyWallets())if(!names.has(x.name))a.push(x);const pref=['Phantom','Solflare','Backpack','MetaMask','Coinbase Wallet','Brave Wallet','Glow','Bags'];return a.sort((a,b)=>(pref.indexOf(a.name)<0?99:pref.indexOf(a.name))-(pref.indexOf(b.name)<0?99:pref.indexOf(b.name)))}
function walletIcon(w){return w.icon||({Phantom:'https://phantom.app/img/phantom-icon-purple.png',Solflare:'https://solflare.com/favicon.ico',Backpack:'https://backpack.app/favicon.ico',MetaMask:'https://upload.wikimedia.org/wikipedia/commons/3/36/MetaMask_Fox.svg','Coinbase Wallet':'https://www.coinbase.com/favicon.ico'}[w.name]||'')}
function renderWalletOptions(){const box=$('#walletOptions');if(!box)return;if(state.address){box.innerHTML=`<div class="wallet-connected-card"><div class="wallet-connected-top"><div class="wallet-avatar">${walletIcon(state.wallet)?`<img src="${walletIcon(state.wallet)}" alt="">`:'◎'}</div><div><small>CONNECTED WALLET</small><strong>${state.wallet?.name||'Solana wallet'}</strong><span>${short(state.address)}</span></div><i>●</i></div><div class="wallet-network"><span>Network</span><b>Solana Devnet</b></div><button id="disconnectWallet" class="disconnect-btn">Disconnect wallet</button></div>`;$('#disconnectWallet').onclick=disconnectWallet;return}const ws=allWallets();if(!ws.length){box.innerHTML='<div class="wallet-empty">No compatible wallet detected. Unlock your wallet extension, then refresh. LeafX supports Wallet Standard-compatible Solana wallets including Phantom, Solflare, Backpack, Coinbase Wallet, Brave Wallet and others.</div>';return}box.innerHTML=ws.map((w,i)=>`<button class="wallet-option" data-wallet-index="${i}"><span class="wallet-brand"><span class="wallet-icon">${walletIcon(w)?`<img src="${walletIcon(w)}" alt="">`:'◎'}</span><span><b>${w.name}</b><small>${w.legacy?'Browser extension':'Wallet Standard'}</small></span></span><span class="wallet-arrow">→</span></button>`).join('');box.querySelectorAll('[data-wallet-index]').forEach(b=>b.onclick=()=>connectWallet(ws[+b.dataset.walletIndex]))}
function goStep(n){state.step=Math.max(1,Math.min(4,n));$$('.step').forEach(x=>x.classList.toggle('active',+x.dataset.step===state.step));$$('.form-step').forEach(x=>x.classList.toggle('active',+x.dataset.panel===state.step));$('#stepLabel').textContent=`STEP ${state.step} OF 4`;updateReview();updateReq()}
$$('.step').forEach(b=>b.onclick=()=>goStep(+b.dataset.step));$$('.next').forEach(b=>b.onclick=()=>goStep(state.step+1));$$('.back').forEach(b=>b.onclick=()=>goStep(state.step-1));$$('[data-scroll]').forEach(b=>b.onclick=()=>$(b.dataset.scroll).scrollIntoView({behavior:'smooth'}));
function updateReview(){const h=$('#xHandle').value||'@creator',s=($('#tokenSymbol').value||'LEAF').toUpperCase();$('#reviewHandle').textContent=h.startsWith('@')?h:'@'+h;$('#reviewToken').textContent='$'+s;$('#reviewPair').textContent='SOL';$('#previewSymbol').textContent='$'+s+' / SOL'}
$('#xHandle').oninput=updateReview;$('#tokenSymbol').oninput=updateReview;$('#tokenName').oninput=()=>$('#previewName').textContent=$('#tokenName').value||'Leaf';
const feeInputs={creator:{input:$('[data-target="creator"]'),range:$('#creatorRange')},holders:{input:$('[data-target="holders"]'),range:$('#holdersRange')},launchpad:{input:$('[data-target="launchpad"]'),range:$('#launchpadRange')}};
function syncFee(k,v){v=Math.max(0,Math.min(100,+v||0));const o=feeInputs[k];o.input.value=v;o.range.value=v;o.input.closest('.fee-row').querySelector('b').textContent=v+'%';const t=Object.values(feeInputs).reduce((s,x)=>s+ +x.input.value,0);$('#feeTotal').textContent=t+'%';$('#feeTotal').style.color=t===100?'var(--green)':'var(--danger)'}Object.entries(feeInputs).forEach(([k,o])=>{o.input.oninput=e=>syncFee(k,e.target.value);o.range.oninput=e=>syncFee(k,e.target.value)});
async function connectWallet(wallet){try{await loadSolana();const w=wallet||allWallets()[0];if(!w)throw Error('No Solana wallet detected. Install and unlock Phantom, Solflare, Backpack, or another compatible wallet, then refresh.');let address=null,account=null;if(w.legacy){if(!w.provider.connect)throw Error(`${w.name} cannot connect from this browser.`);const r=await w.provider.connect();address=r?.publicKey?.toString?.()||w.provider.publicKey?.toString?.();if(!address)throw Error(`${w.name} did not return a Solana address.`);account={address,chains:[SOLANA_CHAIN]}}else{const f=w.features?.['standard:connect'];if(!f)throw Error(`${w.name} does not expose Wallet Standard connect.`);const r=await f.connect();const ac=r?.accounts?.length?r.accounts:w.accounts;account=ac?.find(x=>x.chains?.includes(SOLANA_CHAIN))||ac?.find(x=>x.address)||ac?.[0];address=account?.address;if(!address)throw Error(`${w.name} did not return a Solana account.`)}state.wallet=w;state.account=account;state.address=address;$('#walletModal').classList.remove('open');await refreshWalletUI();toast(`${w.name} connected · Solana Devnet ✓`)}catch(e){console.error(e);toast(e.message||'Wallet connection failed')}}
async function disconnectWallet(){try{const w=state.wallet;const f=w?.features?.['standard:disconnect'];if(f?.disconnect)await f.disconnect();else if(w?.provider?.disconnect)await w.provider.disconnect()}catch(e){console.warn('Wallet disconnect request failed',e)}state.wallet=null;state.account=null;state.address=null;$('#walletBtn').textContent='Connect wallet';$('#dashAddress').textContent='—';$('#dashBalance').textContent='—';$('#dashChain').textContent='—';$('#dashNetwork').textContent='Connect a Solana wallet';$('#networkStatus').innerHTML='<i></i> Wallet not connected';updateReq();renderWalletOptions();toast('Wallet disconnected')}
async function refreshWalletUI(){if(!state.address)return;const p=new state.web3.PublicKey(state.address),b=await state.connection.getBalance(p);$('#walletBtn').textContent=short(state.address);$('#dashAddress').textContent=short(state.address);$('#dashBalance').textContent=sol(b/1e9)+' SOL';$('#dashChain').textContent='Devnet';$('#dashNetwork').textContent=`Connected via ${state.wallet?.name||'Solana wallet'}`;$('#networkStatus').innerHTML='<i></i> Solana Devnet connected';updateReq();renderWalletOptions()}
function updateReq(){const e=$('#walletRequirement');if(!e)return;if(!state.address){e.textContent='Connect a Solana wallet on Devnet before launching.';e.className='wallet-requirement warning'}else{e.textContent=`Connected: ${short(state.address)} · Solana Devnet`;e.className='wallet-requirement connected'}}
$('#walletBtn').onclick=async()=>{await loadSolana();if(state.address){$('#walletModal').classList.add('open');renderWalletOptions()}else{$('#walletModal').classList.add('open');renderWalletOptions()}};$('#walletModal .modal-close').onclick=()=>$('#walletModal').classList.remove('open');$('#walletModal').onclick=e=>{if(e.target.id==='walletModal')e.target.classList.remove('open')};
function b58(bytes){const abc='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';let n=0n;for(const x of bytes)n=(n<<8n)+BigInt(x);let s='';while(n){s=abc[Number(n%58n)]+s;n/=58n}for(const x of bytes){if(x===0)s='1'+s;else break}return s||'1'}
async function sendWallet(tx){if(state.wallet?.legacy){const r=await state.wallet.provider.signAndSendTransaction(tx);return r?.signature||r?.txid||r?.result||r}const f=state.wallet?.features?.['solana:signAndSendTransaction'];if(!f)throw Error(`${state.wallet?.name||'Wallet'} cannot sign/send Solana transactions.`);const bytes=tx.serialize({requireAllSignatures:false,verifySignatures:false});const out=await f.signAndSendTransaction({transaction:bytes,account:state.account,chain:SOLANA_CHAIN});const sig=out?.[0]?.signature;if(!sig)throw Error('Wallet returned no transaction signature.');return typeof sig==='string'?sig:b58(sig)}
async function createMint(){await loadSolana();if(!state.address)throw Error('Connect a Solana wallet first.');const{PublicKey,Keypair,SystemProgram,Transaction}=state.web3,s=state.spl,payer=new PublicKey(state.address),mint=Keypair.generate(),rent=await state.connection.getMinimumBalanceForRentExemption(s.MINT_SIZE),bh=await state.connection.getLatestBlockhash('confirmed'),tx=new Transaction({recentBlockhash:bh.blockhash,feePayer:payer});tx.add(SystemProgram.createAccount({fromPubkey:payer,newAccountPubkey:mint.publicKey,space:s.MINT_SIZE,lamports:rent,programId:s.TOKEN_PROGRAM_ID}));tx.add(s.createInitializeMintInstruction(mint.publicKey,9,payer,payer,s.TOKEN_PROGRAM_ID));tx.partialSign(mint);const sig=await sendWallet(tx);await state.connection.confirmTransaction({signature:sig,blockhash:bh.blockhash,lastValidBlockHeight:bh.lastValidBlockHeight},'confirmed');return{sig,mint:mint.publicKey.toBase58()}}
$('#launchForm').onsubmit=async e=>{e.preventDefault();const total=Object.values(feeInputs).reduce((s,o)=>s+ +o.input.value,0);if(total!==100)return toast('Fee allocation must total 100%.');try{if(!state.address){await loadSolana();$('#walletModal').classList.add('open');renderWalletOptions();return}toast(`Confirm the ${state.wallet.name} transaction…`);const r=await createMint();$('#launchForm').style.display='none';$('#success').classList.add('show');$('#successText').innerHTML=`<b>$${($('#tokenSymbol').value||'LEAF').toUpperCase()}</b> SPL mint created on Solana Devnet.<br><small>Mint: ${r.mint}<br>Transaction: ${r.sig}</small>`;$('#txLink').href=`${EXPLORER}/tx/${r.sig}?cluster=devnet`,$('#mintLink').href=`${EXPLORER}/address/${r.mint}?cluster=devnet`;toast('SPL mint confirmed on Devnet ✓');await refreshWalletUI()}catch(e){console.error(e);toast(e.message||'Solana transaction failed')}};
$('#reset').onclick=()=>{$('#launchForm').style.display='block';$('#success').classList.remove('show');goStep(1);syncFee('creator',45);syncFee('holders',45);syncFee('launchpad',10)};
const launches=[['$PAID','Paid','@leafdotfun','+12.8%','trending','184K'],['$STNK','STonk','@marketleaf','+8.4%','trending','92K'],['$MINT','Mint','@mintcreator','+21.6%','creator','61K'],['$LOOP','Loop','@loopx','+5.2%','creator','44K'],['$BUD','Bud','@budsocial','+17.1%','trending','77K'],['$NOVA','Nova','@novaonx','+3.7%','creator','31K']];function card(x,i){return `<article class="launch-card"><div class="launch-head"><div class="mini-coin">${x[0][1]}</div><span class="trend">${x[3]}</span></div><h3>${x[0]} · ${x[1]}</h3><div class="handle">${x[2]} · paired with SOL</div><div class="spark"><svg viewBox="0 0 260 55" preserveAspectRatio="none"><path d="M0 46 ${[...Array(10)].map((_,j)=>`L${j*29} ${44-Math.sin(j+i)*12-j*2}`).join(' ')} L290 7" fill="none" stroke="#38df8d" stroke-width="2"/></svg></div><div class="launch-meta"><span>LIQUIDITY ${x[5]} SOL</span><span>DEVNET</span></div></article>`}function render(f='all'){$('#launchGrid').innerHTML=launches.filter(x=>f==='all'||x[4]===f).map(card).join('')}render();$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)});
const canvas=$('#chart'),ctx=canvas.getContext('2d');function drawChart(){const d=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);ctx.beginPath();[.76,.72,.74,.68,.69,.63,.58,.62,.55,.57,.49,.52,.45,.47,.42,.44,.37,.38,.29,.31,.26,.21,.22,.18,.12,.13].forEach((v,i)=>{const x=i*w/25,y=v*h;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle='#35e28a';ctx.lineWidth=2;ctx.stroke()}new ResizeObserver(drawChart).observe(canvas);drawChart();
$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');const l=document.body.classList.contains('light'),v=l?['#f3f7f4','#fff','#f0f6f2','#0a1a11','#607168','#d5e1da']:['#06100b','#0b1711','#0f1e16','#f3faf5','#9eaea4','#203127'];['--bg','--panel','--panel2','--text','--muted','--line'].forEach((k,i)=>document.documentElement.style.setProperty(k,v[i]))};
const walletStyle=document.createElement('style');walletStyle.textContent=`.wallet-option{width:100%;display:flex;align-items:center;justify-content:space-between;gap:14px;padding:14px 15px;margin:8px 0;border:1px solid rgba(157,255,205,.11);border-radius:16px;background:linear-gradient(135deg,rgba(255,255,255,.045),rgba(77,255,157,.025));color:var(--text);cursor:pointer;transition:.2s;text-align:left}.wallet-option:hover{transform:translateY(-1px);border-color:rgba(77,255,157,.38);background:linear-gradient(135deg,rgba(77,255,157,.1),rgba(255,255,255,.045));box-shadow:0 12px 30px rgba(0,0,0,.18)}.wallet-brand{display:flex;align-items:center;gap:12px}.wallet-icon,.wallet-avatar{width:42px;height:42px;border-radius:13px;display:grid;place-items:center;background:#101d16;border:1px solid rgba(157,255,205,.13);overflow:hidden;font-weight:900}.wallet-icon img,.wallet-avatar img{width:27px;height:27px;object-fit:contain}.wallet-brand b{display:block;font-size:13px}.wallet-brand small{display:block;margin-top:3px;color:var(--muted);font-size:9px}.wallet-arrow{font-size:20px;color:var(--green)}.wallet-connected-card{padding:6px 0}.wallet-connected-top{display:flex;align-items:center;gap:13px;padding:14px;border:1px solid rgba(77,255,157,.2);border-radius:18px;background:linear-gradient(145deg,rgba(44,113,72,.18),rgba(255,255,255,.025));position:relative}.wallet-connected-top>div:nth-child(2){flex:1}.wallet-connected-top small{display:block;color:var(--green);font-size:8px;letter-spacing:.14em;font-weight:900}.wallet-connected-top strong{display:block;font-size:14px;margin-top:4px}.wallet-connected-top span{display:block;color:var(--muted);font-size:10px;margin-top:3px}.wallet-connected-top>i{font-style:normal;color:var(--green);font-size:10px}.wallet-network{display:flex;justify-content:space-between;padding:13px 4px;color:var(--muted);font-size:10px}.wallet-network b{color:var(--text)}.disconnect-btn{width:100%;padding:12px;border-radius:13px;border:1px solid rgba(255,107,122,.22);background:rgba(255,107,122,.06);color:#ff9ca7;font-weight:800;cursor:pointer;transition:.2s}.disconnect-btn:hover{background:rgba(255,107,122,.12);border-color:rgba(255,107,122,.4)}#walletBtn{min-width:132px}.wallet-empty{padding:16px;border:1px dashed rgba(157,255,205,.13);border-radius:15px;color:var(--muted);font-size:11px;line-height:1.6;text-align:center}.modal-card{width:min(440px,calc(100vw - 28px))!important;border:1px solid rgba(115,255,177,.18)!important;box-shadow:0 30px 100px rgba(0,0,0,.55),0 0 80px rgba(37,210,123,.06)!important}.modal-card h3{font-size:27px!important;letter-spacing:-.04em!important;margin:8px 0!important}.modal-card>p{font-size:11px!important;color:var(--muted)!important;line-height:1.6!important;margin-bottom:18px!important}`;document.head.appendChild(walletStyle);
loadSolana().catch(e=>console.warn('Solana wallet layer unavailable',e));