const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const SOLANA_CHAIN='solana:devnet',RPC_URL='https://api.devnet.solana.com',EXPLORER='https://explorer.solana.com';
const state={step:1,wallet:null,account:null,address:null,web3:null,spl:null,connection:null};let walletRegistry=null;
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),3200)}
function short(a){return a?`${a.slice(0,4)}…${a.slice(-4)}`:'—'}function sol(v){return Number(v).toFixed(4)}
async function loadSolana(){if(state.web3&&state.spl&&walletRegistry)return;const[{Connection,PublicKey,Keypair,SystemProgram,Transaction},spl,std]=await Promise.all([import('https://esm.sh/@solana/web3.js@1.98.4'),import('https://esm.sh/@solana/spl-token@0.4.14'),import('https://esm.sh/@wallet-standard/app@1.1.0')]);state.web3={Connection,PublicKey,Keypair,SystemProgram,Transaction};state.spl=spl;walletRegistry=std.getWallets();state.connection=new Connection(RPC_URL,'confirmed');renderWalletOptions()}
function wallets(){return walletRegistry?[...walletRegistry.get()].filter(w=>w.chains?.some(c=>c===SOLANA_CHAIN||c==='solana:mainnet')).filter((w,i,a)=>a.findIndex(x=>x.name===w.name)===i):[]}
function renderWalletOptions(){const box=$('#walletOptions');if(!box)return;let ws=wallets();const pref=['MetaMask','Phantom','Solflare','Backpack','Bags'];ws.sort((a,b)=>(pref.indexOf(a.name)<0?99:pref.indexOf(a.name))-(pref.indexOf(b.name)<0?99:pref.indexOf(b.name)));box.innerHTML=ws.length?ws.map((w,i)=>`<button class="wallet-option" data-wallet-index="${i}"><span class="wallet-brand"><img src="${w.icon||''}" alt="" onerror="this.style.display='none'"><b>${w.name}</b></span><span>→</span></button>`).join(''):`<div class="wallet-empty">No compatible Solana wallet detected. Install Phantom, Solflare, Backpack, MetaMask with Solana enabled, or another Wallet Standard wallet.</div>`;box.querySelectorAll('[data-wallet-index]').forEach(b=>b.onclick=()=>connectWallet(ws[+b.dataset.walletIndex]))}
function goStep(n){state.step=Math.max(1,Math.min(4,n));$$('.step').forEach(x=>x.classList.toggle('active',+x.dataset.step===state.step));$$('.form-step').forEach(x=>x.classList.toggle('active',+x.dataset.panel===state.step));$('#stepLabel').textContent=`STEP ${state.step} OF 4`;updateReview();updateReq()}
$$('.step').forEach(b=>b.onclick=()=>goStep(+b.dataset.step));$$('.next').forEach(b=>b.onclick=()=>goStep(state.step+1));$$('.back').forEach(b=>b.onclick=()=>goStep(state.step-1));$$('[data-scroll]').forEach(b=>b.onclick=()=>$(b.dataset.scroll).scrollIntoView({behavior:'smooth'}));
function updateReview(){const h=$('#xHandle').value||'@creator',s=($('#tokenSymbol').value||'LEAF').toUpperCase();$('#reviewHandle').textContent=h.startsWith('@')?h:'@'+h;$('#reviewToken').textContent='$'+s;$('#reviewPair').textContent='SOL';$('#previewSymbol').textContent='$'+s+' / SOL'}
$('#xHandle').oninput=updateReview;$('#tokenSymbol').oninput=updateReview;$('#tokenName').oninput=()=>$('#previewName').textContent=$('#tokenName').value||'Leaf';
const feeInputs={creator:{input:$('[data-target="creator"]'),range:$('#creatorRange')},holders:{input:$('[data-target="holders"]'),range:$('#holdersRange')},launchpad:{input:$('[data-target="launchpad"]'),range:$('#launchpadRange')}};
function syncFee(k,v){v=Math.max(0,Math.min(100,+v||0));const o=feeInputs[k];o.input.value=v;o.range.value=v;o.input.closest('.fee-row').querySelector('b').textContent=v+'%';const t=Object.values(feeInputs).reduce((s,x)=>s+ +x.input.value,0);$('#feeTotal').textContent=t+'%';$('#feeTotal').style.color=t===100?'var(--green)':'var(--danger)'}Object.entries(feeInputs).forEach(([k,o])=>{o.input.oninput=e=>syncFee(k,e.target.value);o.range.oninput=e=>syncFee(k,e.target.value)});
async function connectWallet(wallet){try{await loadSolana();const w=wallet||wallets()[0];if(!w)throw Error('No Solana wallet detected.');const f=w.features?.['standard:connect'];if(!f)throw Error(`${w.name} does not support Wallet Standard connection.`);const r=await f.connect();const ac=r?.accounts?.length?r.accounts:w.accounts;const a=ac?.find(x=>x.chains?.includes(SOLANA_CHAIN))||ac?.[0];if(!a)throw Error(`${w.name} did not return a Solana account.`);state.wallet=w;state.account=a;state.address=a.address;$('#walletModal').classList.remove('open');await refreshWalletUI();toast(`${w.name} connected · Solana Devnet ✓`)}catch(e){console.error(e);toast(e.message||'Wallet connection failed')}}
async function refreshWalletUI(){if(!state.address)return;const p=new state.web3.PublicKey(state.address),b=await state.connection.getBalance(p);$('#walletBtn').textContent=short(state.address);$('#dashAddress').textContent=short(state.address);$('#dashBalance').textContent=sol(b/1e9)+' SOL';$('#dashChain').textContent='Devnet';$('#dashNetwork').textContent=`Connected via ${state.wallet?.name||'Solana wallet'}`;$('#networkStatus').innerHTML='<i></i> Solana Devnet connected';updateReq()}
function updateReq(){const e=$('#walletRequirement');if(!e)return;if(!state.address){e.textContent='Connect a Solana wallet on Devnet before launching.';e.className='wallet-requirement warning'}else{e.textContent=`Connected: ${short(state.address)} · Solana Devnet`;e.className='wallet-requirement connected'}}
$('#walletBtn').onclick=async()=>{await loadSolana();if(state.address)await refreshWalletUI();else{$('#walletModal').classList.add('open');renderWalletOptions()}};$('#walletModal .modal-close').onclick=()=>$('#walletModal').classList.remove('open');$('#walletModal').onclick=e=>{if(e.target.id==='walletModal')e.target.classList.remove('open')};
function b58(bytes){const abc='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';let n=0n;for(const x of bytes)n=(n<<8n)+BigInt(x);let s='';while(n){s=abc[Number(n%58n)]+s;n/=58n}for(const x of bytes){if(x===0)s='1'+s;else break}return s||'1'}
async function sendWallet(tx){const f=state.wallet?.features?.['solana:signAndSendTransaction'];if(!f)throw Error(`${state.wallet?.name||'Wallet'} cannot sign/send Solana transactions.`);const bytes=tx.serialize({requireAllSignatures:false,verifySignatures:false});const out=await f.signAndSendTransaction({transaction:bytes,account:state.account,chain:SOLANA_CHAIN});const sig=out?.[0]?.signature;if(!sig)throw Error('Wallet returned no transaction signature.');return typeof sig==='string'?sig:b58(sig)}
async function createMint(){await loadSolana();if(!state.address)throw Error('Connect a Solana wallet first.');const{PublicKey,Keypair,SystemProgram,Transaction}=state.web3,s=state.spl,payer=new PublicKey(state.address),mint=Keypair.generate(),rent=await state.connection.getMinimumBalanceForRentExemption(s.MINT_SIZE),bh=await state.connection.getLatestBlockhash('confirmed'),tx=new Transaction({recentBlockhash:bh.blockhash,feePayer:payer});tx.add(SystemProgram.createAccount({fromPubkey:payer,newAccountPubkey:mint.publicKey,space:s.MINT_SIZE,lamports:rent,programId:s.TOKEN_PROGRAM_ID}));tx.add(s.createInitializeMintInstruction(mint.publicKey,9,payer,payer,s.TOKEN_PROGRAM_ID));tx.partialSign(mint);const sig=await sendWallet(tx);await state.connection.confirmTransaction({signature:sig,blockhash:bh.blockhash,lastValidBlockHeight:bh.lastValidBlockHeight},'confirmed');return{sig,mint:mint.publicKey.toBase58()}}
$('#launchForm').onsubmit=async e=>{e.preventDefault();const total=Object.values(feeInputs).reduce((s,o)=>s+ +o.input.value,0);if(total!==100)return toast('Fee allocation must total 100%.');try{if(!state.address){await loadSolana();$('#walletModal').classList.add('open');renderWalletOptions();return}toast(`Confirm the ${state.wallet.name} transaction…`);const r=await createMint();$('#launchForm').style.display='none';$('#success').classList.add('show');$('#successText').innerHTML=`<b>$${($('#tokenSymbol').value||'LEAF').toUpperCase()}</b> SPL mint created on Solana Devnet.<br><small>Mint: ${r.mint}<br>Transaction: ${r.sig}</small>`;$('#txLink').href=`${EXPLORER}/tx/${r.sig}?cluster=devnet`;$('#mintLink').href=`${EXPLORER}/address/${r.mint}?cluster=devnet`;toast('SPL mint confirmed on Devnet ✓');await refreshWalletUI()}catch(e){console.error(e);toast(e.message||'Solana transaction failed')}};
$('#reset').onclick=()=>{$('#launchForm').style.display='block';$('#success').classList.remove('show');goStep(1);syncFee('creator',45);syncFee('holders',45);syncFee('launchpad',10)};
const launches=[['$PAID','Paid','@leafdotfun','+12.8%','trending','184K'],['$STNK','STonk','@marketleaf','+8.4%','trending','92K'],['$MINT','Mint','@mintcreator','+21.6%','creator','61K'],['$LOOP','Loop','@loopx','+5.2%','creator','44K'],['$BUD','Bud','@budsocial','+17.1%','trending','77K'],['$NOVA','Nova','@novaonx','+3.7%','creator','31K']];function card(x,i){return `<article class="launch-card"><div class="launch-head"><div class="mini-coin">${x[0][1]}</div><span class="trend">${x[3]}</span></div><h3>${x[0]} · ${x[1]}</h3><div class="handle">${x[2]} · paired with SOL</div><div class="spark"><svg viewBox="0 0 260 55" preserveAspectRatio="none"><path d="M0 46 ${[...Array(10)].map((_,j)=>`L${j*29} ${44-Math.sin(j+i)*12-j*2}`).join(' ')} L290 7" fill="none" stroke="#38df8d" stroke-width="2"/></svg></div><div class="launch-meta"><span>LIQUIDITY ${x[5]} SOL</span><span>DEVNET</span></div></article>`}function render(f='all'){$('#launchGrid').innerHTML=launches.filter(x=>f==='all'||x[4]===f).map(card).join('')}render();$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)});
const canvas=$('#chart'),ctx=canvas.getContext('2d');function drawChart(){const d=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);ctx.beginPath();[.76,.72,.74,.68,.69,.63,.58,.62,.55,.57,.49,.52,.45,.47,.42,.44,.37,.38,.29,.31,.26,.21,.22,.18,.12,.13].forEach((v,i)=>{const x=i*w/25,y=v*h;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle='#35e28a';ctx.lineWidth=2;ctx.stroke()}new ResizeObserver(drawChart).observe(canvas);drawChart();
$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');const l=document.body.classList.contains('light'),v=l?['#f3f7f4','#fff','#f0f6f2','#0a1a11','#607168','#d5e1da']:['#06100b','#0b1711','#0f1e16','#f3faf5','#9eaea4','#203127'];['--bg','--panel','--panel2','--text','--muted','--line'].forEach((k,i)=>document.documentElement.style.setProperty(k,v[i]))};
loadSolana().catch(e=>console.warn('Solana wallet layer unavailable',e));
