(() => {
  'use strict';
  const $ = (s, r=document) => r.querySelector(s);
  const $$ = (s, r=document) => [...r.querySelectorAll(s)];
  const DEVNET='devnet';
  const key='leafx_launches_v1';
  const launches=()=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}};
  const save=(x)=>localStorage.setItem(key,JSON.stringify(x.slice(0,50)));
  const fmt=(n)=>n==null||n===''?'—':Number(n).toLocaleString();
  function addShell(){
    if($('#leafxFeatureSuite')) return;
    const el=document.createElement('section'); el.id='leafxFeatureSuite'; el.className='lx-suite';
    el.innerHTML=`<div class="lx-suite-head"><div><div class="lx-eyebrow">LEAFX TERMINAL</div><h2>Trade, track & discover</h2><p>Devnet-first tools for launches, analytics and portfolio tracking.</p></div><span class="lx-network"><i></i> SOLANA DEVNET</span></div>
    <div class="lx-tabs"><button class="active" data-tab="discover">Discover</button><button data-tab="terminal">Trading terminal</button><button data-tab="portfolio">Portfolio</button><button data-tab="analytics">Analytics</button><button data-tab="creator">Creator</button></div>
    <div class="lx-panel active" data-panel="discover"><div class="lx-toolbar"><input id="lxSearch" placeholder="Search token, symbol or mint…"><div class="lx-filters"><button class="active" data-filter="all">All</button><button data-filter="new">New</button><button data-filter="trending">Trending</button><button data-filter="graduated">Graduated</button></div></div><div id="lxTokenGrid" class="lx-grid"></div></div>
    <div class="lx-panel" data-panel="terminal"><div class="lx-terminal"><div class="lx-chartbox"><div class="lx-tokenhead"><div class="lx-avatar">L</div><div><strong id="lxTermName">Select a launch</strong><span id="lxTermPair">—</span></div><span class="lx-live">DEVNET</span></div><div class="lx-chart-placeholder"><span>Price chart</span><b>Live market data will appear after the trading program is deployed.</b></div></div><aside class="lx-tradebox"><div class="lx-trade-tabs"><button class="active">Buy</button><button>Sell</button></div><label>Amount<input id="lxTradeAmount" type="number" min="0" step="any" placeholder="0.00 SOL"></label><div class="lx-quote"><span>Est. output</span><b>—</b></div><button id="lxTradeBtn" class="lx-trade-btn">Connect wallet to trade</button><small>Trading is disabled until LeafX's bonding-curve program is deployed and audited.</small></aside></div></div>
    <div class="lx-panel" data-panel="portfolio"><div class="lx-statgrid"><article><small>WALLET</small><strong id="lxPortWallet">Not connected</strong></article><article><small>PORTFOLIO VALUE</small><strong>—</strong></article><article><small>24H P&amp;L</small><strong>—</strong></article><article><small>HOLDINGS</small><strong id="lxHoldingCount">0</strong></article></div><div class="lx-empty">Connect a wallet and confirmed token activity will appear here.</div></div>
    <div class="lx-panel" data-panel="analytics"><div class="lx-statgrid"><article><small>MARKET CAP</small><strong>—</strong></article><article><small>24H VOLUME</small><strong>—</strong></article><article><small>HOLDERS</small><strong>—</strong></article><article><small>TRANSACTIONS</small><strong>—</strong></article></div><div class="lx-empty">No fake market numbers: live analytics will be populated from indexed Devnet trades.</div></div>
    <div class="lx-panel" data-panel="creator"><div class="lx-creator"><div><div class="lx-eyebrow">CREATOR DASHBOARD</div><h3>Your launch performance</h3><p>Launches, holders, volume and protocol fees will populate from confirmed on-chain activity.</p></div><div class="lx-statgrid"><article><small>LAUNCHES</small><strong id="lxCreatorLaunches">0</strong></article><article><small>HOLDERS</small><strong>—</strong></article><article><small>VOLUME</small><strong>—</strong></article><article><small>FEES</small><strong>—</strong></article></div></div></div>`;
    $('#explore')?.insertAdjacentElement('afterend',el) || document.querySelector('main')?.appendChild(el);
    $$('.lx-tabs button',el).forEach(b=>b.onclick=()=>{$$('.lx-tabs button',el).forEach(x=>x.classList.toggle('active',x===b));$$('.lx-panel',el).forEach(p=>p.classList.toggle('active',p.dataset.panel===b.dataset.tab));render();});
    $$('.lx-filters button',el).forEach(b=>b.onclick=()=>{$$('.lx-filters button',el).forEach(x=>x.classList.toggle('active',x===b));render();});
    $('#lxSearch',el).oninput=render;
  }
  function render(){
    const grid=$('#lxTokenGrid'); if(!grid)return; const q=($('#lxSearch')?.value||'').toLowerCase(); const filter=$('.lx-filters button.active')?.dataset.filter||'all'; let data=launches().filter(x=>!q||`${x.name} ${x.symbol} ${x.mint}`.toLowerCase().includes(q)); if(filter==='new')data=data.slice(0,12); if(filter==='graduated')data=data.filter(x=>x.graduated); if(filter==='trending')data=data.filter(x=>x.volume); grid.innerHTML=data.length?data.map(x=>`<article class="lx-token" data-mint="${x.mint||''}"><div class="lx-token-cover" style="${x.banner?`background-image:url('${x.banner}')`:''}"><span>${x.banner?'':'LEAFX'}</span><em>${x.graduated?'GRADUATED':'DEVNET'}</em></div><div class="lx-token-body"><div><strong>$${x.symbol||'TOKEN'}</strong><small>${x.name||'Unnamed token'}</small></div><button class="lx-open" data-mint="${x.mint||''}">Open</button></div><div class="lx-token-stats"><span>MC <b>—</b></span><span>VOL <b>—</b></span><span>Holders <b>—</b></span></div></article>`).join(''):`<div class="lx-empty">No launches found. Create a Devnet launch to populate Discover.</div>`;
    $$('.lx-open',grid).forEach(b=>b.onclick=()=>selectToken(b.dataset.mint));
    $('#lxCreatorLaunches').textContent=launches().length; $('#lxHoldingCount').textContent=0;
  }
  function selectToken(mint){const x=launches().find(v=>v.mint===mint);if(!x)return;$('.lx-tabs button[data-tab="terminal"]')?.click();$('#lxTermName').textContent=`$${x.symbol||'TOKEN'}`;$('#lxTermPair').textContent=`${x.symbol||'TOKEN'} / ${x.pair||'SOL'}`;}
  function captureSuccess(){const success=$('#success'); if(!success||success.__lxBound)return;success.__lxBound=true;const observer=new MutationObserver(()=>{if(success.classList.contains('show')){const text=$('#successText')?.textContent||'';const mint=(text.match(/Mint:\s*([1-9A-HJ-NP-Za-km-z]{32,44})/)||[])[1];const symbol=(($('#tokenSymbol')?.value||'LEAF')).toUpperCase();const name=$('#tokenName')?.value||'Leaf';if(mint){const arr=launches().filter(x=>x.mint!==mint);arr.unshift({mint,symbol,name,pair:$('#pair')?.value||'SOL',banner:window.__leafxBanner||'',description:$('#tokenDescription')?.value||'',createdAt:Date.now()});save(arr);render();}}});observer.observe(success,{attributes:true,attributeFilter:['class']});}
  function addAdvancedFields(){const form=$('#launchForm');const identity=$('[data-panel="1"]',form);if(identity&&!$('#tokenDescription')){const wrap=document.createElement('div');wrap.className='lx-launch-fields';wrap.innerHTML=`<label>X profile link<input id="xProfile" type="url" placeholder="https://x.com/yourprofile"></label><label>Token banner<input id="tokenBanner" type="file" accept="image/png,image/jpeg,image/webp"></label><label>Token description<textarea id="tokenDescription" maxlength="500" placeholder="Tell people what this token is about…"></textarea><small id="lxDescCount">0 / 500</small></div>`;identity.querySelector('.next')?.before(wrap);$('#tokenBanner').onchange=e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>3*1024*1024){e.target.value='';return alert('Banner must be 3 MB or smaller.')}const r=new FileReader();r.onload=()=>window.__leafxBanner=r.result;r.readAsDataURL(f)};$('#tokenDescription').oninput=e=>$('#lxDescCount').textContent=`${e.target.value.length} / 500`;}}
  function forceDevnetLabels(){ $$('*').forEach(el=>{if(el.children.length===0&&/MAINNET/.test(el.textContent))el.textContent=el.textContent.replace(/MAINNET/g,'DEVNET')}); const hero=document.querySelector('.eyebrow'); }
  function init(){addShell();addAdvancedFields();captureSuccess();forceDevnetLabels();render();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
