(()=>{
const RPCS=['https://api.devnet.solana.com'];
const CHAIN='solana:devnet';
const $=s=>document.querySelector(s);
const toast=m=>{const t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');clearTimeout(window.__lv3toast);window.__lv3toast=setTimeout(()=>t.classList.remove('show'),5000)};
let libsCache=null;
async function libs(){if(libsCache)return libsCache;libsCache=Promise.all([import('https://esm.sh/@solana/web3.js@1.98.4'),import('https://esm.sh/@solana/spl-token@0.4.14'),import('https://esm.sh/@wallet-standard/app@1.1.0')]).then(([web3,spl,std])=>({web3,spl,std}));return libsCache}
function provider(){if(window.phantom?.solana?.isConnected)return ['Phantom',window.phantom.solana];if(window.solflare?.isConnected)return ['Solflare',window.solflare];if(window.backpack?.solana?.isConnected)return ['Backpack',window.backpack.solana];if(window.braveSolana?.isConnected)return ['Brave Wallet',window.braveSolana];if(window.coinbaseSolana?.isConnected)return ['Coinbase Wallet',window.coinbaseSolana];return null}
async function walletAccount(){const p=provider();if(p)return {name:p[0],provider:p[1],address:p[1].publicKey?.toString?.()};const {std}=await libs();const reg=std.getWallets();for(const w of reg.get()){const a=(w.accounts||[]).find(a=>a.chains?.includes(CHAIN));if(a)return {name:w.name,wallet:w,account:a,address:a.address}}throw Error('Connect a Solana wallet first.');}
function sendTx(tx,w){if(w.provider?.signAndSendTransaction)return w.provider.signAndSendTransaction(tx).then(r=>r?.signature||r?.txid||r);const f=w.wallet?.features?.['solana:signAndSendTransaction'];if(!f)throw Error(`${w.name} cannot sign Solana transactions in this browser.`);const bytes=tx.serialize({requireAllSignatures:false,verifySignatures:false});return f.signAndSendTransaction({transaction:bytes,account:w.account,chain:CHAIN}).then(out=>{const s=out?.[0]?.signature;if(!s)throw Error('Wallet returned no transaction signature.');if(typeof s==='string')return s;const abc='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';let n=0n,o='';for(const b of s)n=(n<<8n)+BigInt(b);while(n){o=abc[Number(n%58n)]+o;n/=58n}for(const b of s){if(b===0)o='1'+o;else break}return o||'1'})}
async function waitForSignature(c,sig,lastHeight){for(let i=0;i<45;i++){const st=await c.getSignatureStatuses([sig]);const v=st?.value?.[0];if(v){if(v.err)throw Error('Solana rejected the transaction: '+JSON.stringify(v.err));if(v.confirmationStatus==='confirmed'||v.confirmationStatus==='finalized')return}const h=await c.getBlockHeight('processed');if(h>lastHeight)throw Error('BLOCKHASH_EXPIRED');await new Promise(r=>setTimeout(r,1200))}throw Error('CONFIRMATION_TIMEOUT')}
async function createToken(){const [{Connection,PublicKey,Keypair,SystemProgram,Transaction},s]=await Promise.all([import('https://esm.sh/@solana/web3.js@1.98.4'),import('https://esm.sh/@solana/spl-token@0.4.14')]);const w=await walletAccount();const payer=new PublicKey(w.address);const decimals=Math.max(0,Math.min(9,Number($('#tokenDecimals')?.value||9)));const supply=Number($('#initialSupply')?.value||0);if(!Number.isFinite(supply)||supply<0)throw Error('Enter a valid initial supply.');const connection=new Connection(RPCS[0],'processed');const balance=await connection.getBalance(payer,'processed');for(let attempt=1;attempt<=3;attempt++){const mint=Keypair.generate();const rent=await connection.getMinimumBalanceForRentExemption(s.MINT_SIZE,'processed');const latest=await connection.getLatestBlockhash('processed');const tx=new Transaction({recentBlockhash:latest.blockhash,feePayer:payer});const ata=s.getAssociatedTokenAddressSync(mint.publicKey,payer,false,s.TOKEN_PROGRAM_ID,s.ASSOCIATED_TOKEN_PROGRAM_ID);tx.add(SystemProgram.createAccount({fromPubkey:payer,newAccountPubkey:mint.publicKey,space:s.MINT_SIZE,lamports:rent,programId:s.TOKEN_PROGRAM_ID}));tx.add(s.createInitializeMintInstruction(mint.publicKey,decimals,payer,null,s.TOKEN_PROGRAM_ID));tx.add(s.createAssociatedTokenAccountInstruction(payer,ata,payer,mint.publicKey,s.TOKEN_PROGRAM_ID,s.ASSOCIATED_TOKEN_PROGRAM_ID));if(supply>0){const units=BigInt(Math.round(supply*10**decimals));if(units>0n)tx.add(s.createMintToInstruction(mint.publicKey,ata,payer,units,[],s.TOKEN_PROGRAM_ID));}tx.partialSign(mint);const fee=await connection.getFeeForMessage(tx.compileMessage(),'processed');const required=rent+(fee.value||5000)+10000;if(balance<required)throw Error(`Not enough Devnet SOL. Need about ${(required/1e9).toFixed(5)} SOL plus fees.`);try{toast(`Confirm ${w.name}: mint + supply…`);const sig=String(await sendTx(tx,w));await waitForSignature(connection,sig,latest.lastValidBlockHeight);return{sig,mint:mint.publicKey.toBase58(),ata:ata.toBase58(),pair:$('#pair')?.value==='SPL'?$('#pairMint')?.value.trim():'SOL',supply,decimals}}catch(e){if(e.message==='BLOCKHASH_EXPIRED'&&attempt<3){toast('Fresh blockhash required — rebuilding transaction…');continue}throw e}}throw Error('Transaction expired after 3 fresh attempts. Try again with the wallet open.');}
function installPairUI(){const pair=$('#pair'),wrap=$('#pairMintWrap');if(!pair||!wrap)return;const update=()=>{wrap.style.display=pair.value==='SPL'?'block':'none';const s=$('#tokenSymbol')?.value||'LEAF';$('#previewSymbol').textContent='$'+s+' / '+(pair.value==='SOL'?'SOL':'SPL');$('#reviewPair').textContent=pair.value==='SOL'?'SOL':($('#pairMint')?.value?$('#pairMint').value.slice(0,4)+'…'+$('#pairMint').value.slice(-4):'SPL asset')};pair.addEventListener('change',update);$('#pairMint')?.addEventListener('input',update);update();const sup=$('#initialSupply');sup?.addEventListener('input',()=>{$('#reviewSupply').textContent=Number(sup.value||0).toLocaleString()});}
function addPoolNotice(){const p=$('#walletRequirement');if(!p)return;const n=document.createElement('div');n.className='pair-note';n.innerHTML='<b>Liquidity pairing</b><span>SOL or any valid Solana SPL/tokenized asset can be selected as the quote asset. Creating the actual AMM pool requires an on-chain pool program; this build records the pair and creates the token first.</span>';p.parentNode.insertBefore(n,p)}
async function submit(e){e.preventDefault();e.stopImmediatePropagation();const total=[...document.querySelectorAll('.fee-input')].reduce((a,x)=>a+Number(x.value||0),0);if(total!==100)return toast('Fee allocation must total 100%.');if($('#pair')?.value==='SPL'){const q=$('#pairMint')?.value.trim();if(!q)return toast('Paste the quote token mint address.');try{const{web3}=await libs();new web3.PublicKey(q)}catch{return toast('Quote token mint address is not valid.')}}const btn=$('#launchForm .launch-btn');if(btn)btn.disabled=true;try{const r=await createToken();$('#launchForm').style.display='none';$('#success')?.classList.add('show');const symbol=($('#tokenSymbol')?.value||'LEAF').toUpperCase();const pair=r.pair==='SOL'?'SOL':r.pair.slice(0,6)+'…'+r.pair.slice(-4);$('#successText').innerHTML=`<b>$${symbol}</b> mint + initial supply created on Solana Devnet.<br><small>Mint: ${r.mint}<br>Supply: ${r.supply.toLocaleString()} · ${r.decimals} decimals<br>Pair asset: ${pair}<br>Token account: ${r.ata}<br>Transaction: ${r.sig}</small>`;$('#txLink').href=`https://explorer.solana.com/tx/${r.sig}?cluster=devnet`;$('#mintLink').href=`https://explorer.solana.com/address/${r.mint}?cluster=devnet`;toast('Mint confirmed on Devnet ✓')}catch(e){console.error(e);const m=String(e.message||e);toast(m==='BLOCKHASH_EXPIRED'?'Transaction expired; LeafX will rebuild it.':m.includes('rejected')||m.includes('User rejected')?'Transaction cancelled in wallet.':m)}finally{if(btn)btn.disabled=false}}
installPairUI();addPoolNotice();const form=$('#launchForm');form?.addEventListener('submit',submit,true);const style=document.createElement('style');style.textContent='.pair-note{margin:12px 0;padding:13px 15px;border:1px solid rgba(87,255,164,.12);border-radius:14px;background:rgba(87,255,164,.035)}.pair-note b{display:block;color:#a6ffca;font-size:11px;margin-bottom:4px}.pair-note span{display:block;color:var(--muted);font-size:9px;line-height:1.5}.launch-btn:disabled{opacity:.55;cursor:wait}';document.head.appendChild(style);
})();