(()=>{
'use strict';
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const form=$('#launchForm');if(!form)return;
let current=1;
const panels=()=>$$('.form-step',form),steps=()=>$$('.step');
function syncReview(){const ticker=($('#launchTicker')?.value||$('#tokenSymbol')?.value||'LEAF').replace(/\$/g,'').toUpperCase(),name=$('#tokenName')?.value||'Leaf',x=$('#xLink')?.value||'',pair=$('#pair')?.value||'SOL',supply=Number($('#initialSupply')?.value||0);const rh=$('#reviewHandle');if(rh)rh.textContent=x?x.replace(/^https?:\/\/(www\.)?x\.com\//,'@').replace(/\/$/,''):'X profile not added';const rt=$('#reviewToken');if(rt)rt.textContent='$'+ticker;const rp=$('#reviewPair');if(rp)rp.textContent=pair;const rs=$('#reviewSupply');if(rs)rs.textContent=supply.toLocaleString();const pn=$('#previewName');if(pn)pn.textContent=name;const ps=$('#previewSymbol');if(ps)ps.textContent='$'+ticker+' / '+pair}
function render(n){current=Math.max(1,Math.min(4,n));panels().forEach(p=>p.classList.toggle('active',Number(p.dataset.panel)===current));steps().forEach(s=>s.classList.toggle('active',Number(s.dataset.step)===current));const l=$('#stepLabel');if(l)l.style.display='none';syncReview();if(typeof window.updateReq==='function')window.updateReq()}
function next(){const panel=panels().find(p=>Number(p.dataset.panel)===current);if(!panel)return;for(const input of $$('input[required],textarea[required],select[required]',panel)){if(!input.checkValidity()){input.reportValidity();return}}if(current===1){const ticker=$('#launchTicker');if(ticker&&!/^[A-Za-z0-9]{2,10}$/.test(ticker.value.trim())){ticker.setCustomValidity('Ticker must be 2–10 letters or numbers.');ticker.reportValidity();return}ticker?.setCustomValidity('')}if(current===3){const total=$$('.fee-input',form).reduce((sum,x)=>sum+(Number(x.value)||0),0);if(total!==100){window.toast?.('Fee allocation must total 100%.');return}}render(current+1)}
function back(){render(current-1)}
document.addEventListener('click',e=>{const n=e.target.closest('#launchForm .next'),b=e.target.closest('#launchForm .back'),s=e.target.closest('.steps .step');if(n){e.preventDefault();e.stopImmediatePropagation();next();return}if(b){e.preventDefault();e.stopImmediatePropagation();back();return}if(s){e.preventDefault();e.stopImmediatePropagation();render(Number(s.dataset.step));return}},true);
const identity=$('.form-step[data-panel="1"]');
if(identity){const oldLabel=$('#xHandle')?.closest('label'),oldPreview=identity.querySelector('.profile-preview');if(oldLabel)oldLabel.style.display='none';if(oldPreview)oldPreview.remove();if(!$('#xLink')){const box=document.createElement('div');box.className='launch-media-fields level7-media';box.innerHTML=`<label class="l7-field">X profile link<input id="xLink" type="url" placeholder="https://x.com/yourprofile" autocomplete="url"><small>Paste the public X profile URL that should appear on your token page.</small></label><label class="l7-field">Token ticker<input id="launchTicker" type="text" maxlength="10" placeholder="LEAF" autocomplete="off" required><small>2–10 letters or numbers. This becomes the token symbol.</small></label><label class="l7-field">Token banner<input id="launchBanner" type="file" accept="image/png,image/jpeg,image/webp"><small>PNG, JPG or WebP · maximum 3 MB</small></label><div id="bannerPreview" class="banner-preview" hidden><span>Banner preview</span></div><label class="l7-field">Token description<textarea id="launchDescription" maxlength="500" rows="4" placeholder="Tell people what this token is about..."></textarea><small><span id="descCount">0</span>/500</small></label>`;identity.querySelector('.panel-title')?.after(box)}const ticker=$('#launchTicker');if(ticker&&!ticker.value)ticker.value=$('#tokenSymbol')?.value||'LEAF';$('#xLink')?.addEventListener('input',syncReview);$('#launchTicker')?.addEventListener('input',()=>{$('#tokenSymbol').value=$('#launchTicker').value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,10);syncReview()});$('#tokenName')?.addEventListener('input',syncReview);$('#pair')?.addEventListener('change',syncReview);$('#initialSupply')?.addEventListener('input',syncReview);$('#launchDescription')?.addEventListener('input',e=>{const c=$('#descCount');if(c)c.textContent=e.target.value.length});$('#launchBanner')?.addEventListener('change',e=>{const f=e.target.files?.[0],p=$('#bannerPreview');if(!f||!p)return;if(f.size>3*1024*1024){e.target.value='';p.hidden=true;window.toast?.('Banner must be 3 MB or smaller.');return}if(!/^image\/(png|jpeg|webp)$/.test(f.type)){e.target.value='';p.hidden=true;window.toast?.('Use PNG, JPG or WebP.');return}p.hidden=false;p.style.backgroundImage=`url("${URL.createObjectURL(f)}")`})}
const reviewCreator=$('#reviewHandle')?.parentElement;if(reviewCreator){const label=reviewCreator.querySelector('span');if(label)label.textContent='X profile'}
const launchButton=$('.launch-btn');if(launchButton){launchButton.innerHTML='Launch token <span>↗</span>';launchButton.setAttribute('aria-label','Launch token')}
if(!$('#level7WizardStyle')){const style=document.createElement('style');style.id='level7WizardStyle';style.textContent=`.level7-media{display:grid;gap:14px;margin:20px 0}.l7-field{display:grid!important;gap:8px}.l7-field input,.l7-field textarea{width:100%;box-sizing:border-box}.l7-field small{font-size:9px!important;color:var(--muted)!important;line-height:1.45}.banner-preview{min-height:150px;border:1px solid rgba(97,255,176,.18);border-radius:18px;background-color:#07110c;background-size:cover;background-position:center;display:flex;align-items:flex-end;padding:12px;box-shadow:inset 0 -70px 80px rgba(0,0,0,.55)}.banner-preview span{font-size:9px;letter-spacing:.12em;text-transform:uppercase;font-weight:900;color:#fff;text-shadow:0 2px 10px #000}.level7-media input[type=file]{padding:12px}.level7-media textarea{resize:vertical;min-height:90px}.section-heading .step-pill{display:none}.steps{gap:8px!important}.steps .step{border:0!important;background:transparent!important;opacity:.45;transition:all .2s ease}.steps .step.active{opacity:1;background:rgba(97,255,176,.06)!important;border-radius:16px!important}.launch-btn{min-height:62px!important;border-radius:18px!important;border:1px solid rgba(255,255,255,.14)!important;background:linear-gradient(135deg,#61ffb0 0%,#9a7cff 100%)!important;color:#05070a!important;font-size:15px!important;font-weight:1000!important;letter-spacing:-.02em;box-shadow:0 18px 55px rgba(97,255,176,.16),inset 0 1px rgba(255,255,255,.5)!important;transition:transform .18s ease,box-shadow .18s ease!important}.launch-btn:hover{transform:translateY(-2px)!important;box-shadow:0 24px 70px rgba(97,255,176,.25),inset 0 1px rgba(255,255,255,.6)!important}.launch-btn span{margin-left:10px;font-size:18px}.form-step[data-panel="4"] .demo-note{opacity:.7;line-height:1.5}.form-step[data-panel="4"] .panel-title h3{font-size:clamp(25px,3vw,38px)!important}`;document.head.appendChild(style)}
render(1);
})();