(()=>{
const RPC='https://api.devnet.solana.com',EXPLORER='https://explorer.solana.com',CHAIN='solana:devnet';
const $=s=>document.querySelector(s);
const toast=m=>{const t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');clearTimeout(window.__leafMintToast);window.__leafMintToast=setTimeout(()=>t.classList.remove('show'),6000)};
const b58=bytes=>{const a='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';let n=0n;for(const b of bytes)n=(n<<8n)+BigInt(b);let s='';while(n){s=a[Number(n%58n)]+s;n/=58n}for(const b of bytes){if(b===0)s='1'+s;else break}return s||'1'};
const units=(value,decimals)=>{const s=String(value??'0').trim();if(!/^\d+(\.\d+)?$/.test(s))throw Error('Initial supply must be a valid number.');const [whole,frac='']=s.split('.');const f=(frac+'0'.repeat(decimals)).slice(0,decimals);return BigInt(whole||'0')*10n**BigInt(decimals)+BigInt(f||'0')};
async function libs(){const [web3,spl]=await Promise.all([import('https://esm.sh/@solana/web3.js@1.98.4'),import('https://esm.sh/@solana/spl-token@0.4.14')]);return{web3,spl}};
function walletName(){return window.__leafConnectedWallet?.name||''}
function providerFor(name){if(name==='Phantom')return window.phantom?.solana||null;if(name==='Solflare')return window.solflare||null;if(name==='Backpack')return window.backpack?.solana||null;if(name==='Brave Wallet')return window.braveSolana||null;if(name==='Coinbase Wallet')return window.coinbaseSolana||null;return null}
async function findStandard(name){try{const m=await import('https://esm.sh/@wallet-standard/app@1.1.0');const r=m.getWallets();const w=[...r.get()].find(x=>x.name===name)||[...r.get()].find(x=>x.chains?.includes(CHAIN));const a=w?.accounts?.find(x=>x.chains?.includes(CHAIN))||w?.accounts?.[0];return w&&a?{wallet:w,account:a}:null}catch{return null}}
async function send(tx,name){const p=providerFor(name);if(p?.signAndSendTransaction){const r=await p.signAndSendTransaction(tx);return String(r?.signature||r?.txid||r)}const w=window.__leafConnectedWallet,account=window.__leafConnectedAccount,f=w?.features?.['solana:signAndSendTransaction'];if(f&&account){const raw=tx.serialize({requireAllSignatures:false,verifySignatures:false});const out=await f.signAndSendTransaction({transaction:raw,account,chain:CHAIN});const sig=out?.[0]?.signature;if(!sig)throw Error('Wallet returned no transaction signature.');return typeof sig==='string'?sig:b58(sig)}const found=await findStandard(name);const sf=found?.wallet?.features?.['solana:signAndSendTransaction'];if(!sf)throw Error(`${name||'This wallet'} cannot sign Solana transactions in this browser.`);const raw=tx.serialize({requireAllSignatures:false,verifySignatures:false});const out=await sf.signAndSendTransaction({transaction:raw,account:found.account,chain:CHAIN});const sig=out?.[0]?.signature;if(!sig)throw Error('Wallet returned no transaction signature.');return typeof sig==='string'?sig:b58(sig)}
async function waitForSignature(connection,sig,lastValidBlockHeight){for(let i=0;i<180;i++){const st=(await connection.getSignatureStatuses([sig],{searchTransactionHistory:true})).value[0];if(st?.err)throw Error(`Transaction rejected on-chain: ${JSON.stringify(st.err)}`);if(st?.confirmationStatus==='confirmed'||st?.confirmationStatus==='finalized')return;const h=await connection.getBlockHeight('confirmed');if(h>lastValidBlockHeight)throw Error('TRANSACTION_EXPIRED');await new Promise(r=>setTimeout(r,500))}throw Error('TRANSACTION_EXPIRED')}
async function mintOnce(){const{web3,spl}=await libs(),connection=new web3.Connection(RPC,'confirmed'),name=walletName(),provider=providerFor(name),payerAddress=provider?.publicKey?.toString?.()||window.__leafConnectedAddress;if(!payerAddress)throw Error('Your wallet address is unavailable. Disconnect and reconnect the wallet.');const payer=new web3.PublicKey(payerAddress),decimals=Math.max(0,Math.min(9,Number($('#tokenDecimals')?.value??9))),supplyText=$('#initialSupply')?.value||'1000000',amount=units(supplyText,decimals);if(amount<=0n)throw Error('Initial supply must be greater than 0.');const balance=await connection.getBalance(payer,'confirmed'),mint=web3.Keypair.generate(),rent=await connection.getMinimumBalanceForRentExemption(spl.MINT_SIZE,'confirmed'),ata=spl.getAssociatedTokenAddressSync(mint.publicKey,payer,false,spl.TOKEN_PROGRAM_ID,spl.ASSOCIATED_TOKEN_PROGRAM_ID),latest=await connection.getLatestBlockhash('processed'),tx=new web3.Transaction({recentBlockhash:latest.blockhash,feePayer:payer});tx.add(web3.SystemProgram.createAccount({fromPubkey:payer,newAccountPubkey:mint.publicKey,space:spl.MINT_SIZE,lamports:rent,programId:spl.TOKEN_PROGRAM_ID}));tx.add(spl.createInitializeMintInstruction(mint.publicKey,decimals,payer,payer,spl.TOKEN_PROGRAM_ID));tx.add(spl.createAssociatedTokenAccountInstruction(payer,ata,payer,mint.publicKey,spl.TOKEN_PROGRAM_ID,spl.ASSOCIATED_TOKEN_PROGRAM_ID));tx.add(spl.createMintToCheckedInstruction(mint.publicKey,ata,payer,amount,decimals,[],spl.TOKEN_PROGRAM_ID));mint.partialSign(mint);const msg=tx.compileMessage(),fee=(await connection.getFeeForMessage(msg,'processed')).value??5000;if(balance<rent+fee+10000)throw Error(`Not enough Devnet SOL. Need about ${((rent+fee+10000)/1e9).toFixed(5)} SOL; wallet has ${(balance/1e9).toFixed(5)} SOL.`);const sig=await send(tx,name);await waitForSignature(connection,sig,latest.lastValidBlockHeight);return{sig,mint:mint.publicKey.toBase58(),ata:ata.toBase58(),supply:supplyText,decimals}}
async function mintWithRetry(){for(let attempt=1;attempt<=3;attempt++){try{return await mintOnce()}catch(e){if(String(e?.message)==='TRANSACTION_EXPIRED'&&attempt<3){toast(`Transaction expired. Building a fresh transaction (${attempt+1}/3)…`);continue}throw e}}throw Error('Transaction expired after 3 attempts. Please try again.')}
const form=$('#launchForm');if(!form)return;form.onsubmit=async e=>{e.preventDefault();e.stopImmediatePropagation();const total=[...document.querySelectorAll('.fee-input')].reduce((s,x)=>s+Number(x.value||0),0);if(total!==100){toast('Fee allocation must total 100%.');return}if(!window.__leafConnectedAddress){$('#walletModal')?.classList.add('open');window.__leafWalletUI?.scan?.();toast('Connect a Solana wallet first.');return}const button=form.querySelector('.launch-btn');if(button){button.disabled=true;button.innerHTML='◎ Preparing secure mint…'}try{toast(`Confirm the ${walletName()||'wallet'} transaction…`);const r=await mintWithRetry();form.style.display='none';$('#success')?.classList.add('show');const symbol=($('#tokenSymbol')?.value||'LEAF').toUpperCase(),name=$('#tokenName')?.value||'Leaf';$('#successText').innerHTML=`<b>${name} · $${symbol}</b> is a real SPL token on Solana Devnet.<br><small>Mint: ${r.mint}<br>Initial supply: ${Number(r.supply).toLocaleString()} · ${r.decimals} decimals<br>Token account: ${r.ata}<br>Transaction: ${r.sig}</small>`;$('#txLink').href=`${EXPLORER}/tx/${r.sig}?cluster=devnet`,$('#mintLink').href=`${EXPLORER}/address/${r.mint}?cluster=devnet`;toast('SPL token created and initial supply minted ✓')}catch(e){console.error(e);const m=String(e?.message||e);toast(/reject|denied|cancel/i.test(m)?'Transaction cancelled in your wallet.':m==='TRANSACTION_EXPIRED'?'Transaction expired. Please try again.':`Mint failed: ${m}`)}finally{if(button){button.disabled=false;button.innerHTML='◎ Create SPL mint & sign <span>↗</span>'}}};
})();
