(() => {
  const NETWORK = 'devnet';
  const RPC = 'https://api.devnet.solana.com';
  const EXPLORER = 'https://explorer.solana.com';
  const CHAIN = 'solana:devnet';
  const $ = (s) => document.querySelector(s);
  window.LEAFX_NETWORK = NETWORK;
  window.LEAFX_RPC = RPC;
  window.LEAFX_EXPLORER = EXPLORER;
  const toast = (msg) => { const t=$('#toast'); if(!t)return; t.textContent=msg; t.classList.add('show'); clearTimeout(window.__leafMintToast); window.__leafMintToast=setTimeout(()=>t.classList.remove('show'),7000); };
  const b58 = (bytes) => { const a='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'; let n=0n; for(const b of bytes)n=(n<<8n)+BigInt(b); let s=''; while(n){s=a[Number(n%58n)]+s;n/=58n;} for(const b of bytes){if(b===0)s='1'+s;else break;} return s||'1'; };
  async function libs(){ return {web3:await import('https://esm.sh/@solana/web3.js@1.98.4'),spl:await import('https://esm.sh/@solana/spl-token@0.4.14')}; }
  function walletName(){ return window.__leafConnectedWallet?.name || ($('#dashNetwork')?.textContent.match(/Connected via (.+)$/)?.[1]||''); }
  function providerFor(name){ if(name==='Phantom')return window.phantom?.solana||null; if(name==='Solflare')return window.solflare||null; if(name==='Backpack')return window.backpack?.solana||null; if(name==='Brave Wallet')return window.braveSolana||null; if(name==='Coinbase Wallet')return window.coinbaseSolana||null; return null; }
  async function findStandard(name){ try{const m=await import('https://esm.sh/@wallet-standard/app@1.1.0');const r=m.getWallets();const w=[...r.get()].find(x=>x.name===name)||[...r.get()].find(x=>x.chains?.includes(CHAIN));if(!w)return null;const a=w.accounts?.find(x=>x.chains?.includes(CHAIN))||w.accounts?.[0];return w&&a?{wallet:w,account:a}:null;}catch{return null;} }
  async function send(tx,name){ const p=providerFor(name); if(p?.signAndSendTransaction){const r=await p.signAndSendTransaction(tx);return r?.signature||r?.txid||r;} const f=window.__leafConnectedWallet?.features?.['solana:signAndSendTransaction'];const account=window.__leafConnectedAccount;if(f&&account){const raw=tx.serialize({requireAllSignatures:false,verifySignatures:false});const out=await f.signAndSendTransaction({transaction:raw,account,chain:CHAIN});const sig=out?.[0]?.signature;if(!sig)throw Error('Wallet returned no transaction signature.');return typeof sig==='string'?sig:b58(sig);}const found=await findStandard(name);if(!found)throw Error('Wallet connection could not be recovered. Disconnect and reconnect your wallet.');const sf=found.wallet.features?.['solana:signAndSendTransaction'];if(!sf)throw Error(`${name} cannot sign Solana transactions in this browser.`);const raw=tx.serialize({requireAllSignatures:false,verifySignatures:false});const out=await sf.signAndSendTransaction({transaction:raw,account:found.account,chain:CHAIN});const sig=out?.[0]?.signature;if(!sig)throw Error('Wallet returned no transaction signature.');return typeof sig==='string'?sig:b58(sig); }
  async function waitForSignature(connection,sig,lastValidBlockHeight){for(let i=0;i<180;i++){const status=(await connection.getSignatureStatuses([sig],{searchTransactionHistory:false})).value[0];if(status?.err)throw Error(`Transaction failed on-chain: ${JSON.stringify(status.err)}`);if(status?.confirmationStatus==='confirmed'||status?.confirmationStatus==='finalized')return;const height=await connection.getBlockHeight('confirmed');if(height>lastValidBlockHeight)throw Error('TRANSACTION_EXPIRED');await new Promise(r=>setTimeout(r,500));}throw Error('TRANSACTION_EXPIRED');}
  function pairConfig(){const pair=$('#pair')?.value||'SOL';return {pair,mint:$('#pairMint')?.value?.trim()||'',initialSupply:Number($('#initialSupply')?.value||1000000),decimals:Number($('#tokenDecimals')?.value||9)};}
  async function validatePair(connection){const cfg=pairConfig();if(cfg.pair==='SOL')return;const {web3,spl}=await libs();const mintAddress=cfg.pair==='USDC'?'4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU':cfg.mint;if(!mintAddress)throw Error('Enter the quote token mint address.');let pk;try{pk=new web3.PublicKey(mintAddress);}catch{throw Error('Quote mint address is invalid.');}const info=await spl.getMint(connection,pk,'confirmed',spl.TOKEN_PROGRAM_ID).catch(()=>null);if(!info)throw Error('Quote mint was not found on Solana Devnet.');}
  async function mintOnce(){const {web3,spl}=await libs();const c=new web3.Connection(RPC,'confirmed');const name=walletName();if(!name)throw Error('Connect a Solana wallet first.');const p=providerFor(name);const payerAddress=p?.publicKey?.toString?.()||window.__leafConnectedAddress;if(!payerAddress)throw Error('Wallet address is unavailable. Disconnect and reconnect.');const payer=new web3.PublicKey(payerAddress);const cfg=pairConfig();if(!Number.isInteger(cfg.decimals)||cfg.decimals<0||cfg.decimals>9)throw Error('Decimals must be between 0 and 9.');if(!Number.isFinite(cfg.initialSupply)||cfg.initialSupply<=0)throw Error('Initial supply must be greater than 0.');await validatePair(c);const balance=await c.getBalance(payer,'confirmed');const rent=await c.getMinimumBalanceForRentExemption(spl.MINT_SIZE,'confirmed');const latest=await c.getLatestBlockhash('confirmed');const mint=web3.Keypair.generate();const ata=spl.getAssociatedTokenAddressSync(mint.publicKey,payer,false,spl.TOKEN_PROGRAM_ID,spl.ASSOCIATED_TOKEN_PROGRAM_ID);const rawSupply=BigInt(Math.round(cfg.initialSupply*(10**cfg.decimals)));const tx=new web3.Transaction({recentBlockhash:latest.blockhash,feePayer:payer});tx.add(web3.SystemProgram.createAccount({fromPubkey:payer,newAccountPubkey:mint.publicKey,space:spl.MINT_SIZE,lamports:rent,programId:spl.TOKEN_PROGRAM_ID}));tx.add(spl.createInitializeMintInstruction(mint.publicKey,cfg.decimals,payer,payer,spl.TOKEN_PROGRAM_ID));tx.add(spl.createAssociatedTokenAccountInstruction(payer,ata,payer,mint.publicKey,spl.TOKEN_PROGRAM_ID,spl.ASSOCIATED_TOKEN_PROGRAM_ID));tx.add(spl.createMintToInstruction(mint.publicKey,ata,payer,rawSupply,[],spl.TOKEN_PROGRAM_ID));tx.partialSign(mint);const msg=tx.compileMessage();const fee=(await c.getFeeForMessage(msg,'confirmed')).value??10000;if(balance<rent+fee+10000)throw Error(`Not enough Devnet SOL. You need about ${((rent+fee+10000)/1e9).toFixed(5)} SOL, but this wallet has ${(balance/1e9).toFixed(5)}.`);const sig=String(await send(tx,name));await waitForSignature(c,sig,latest.lastValidBlockHeight);return {sig,mint:mint.publicKey.toBase58(),ata:ata.toBase58()};}
  async function mintWithRetry(){for(let attempt=1;attempt<=3;attempt++){try{return await mintOnce();}catch(e){if(String(e?.message)==='TRANSACTION_EXPIRED'&&attempt<3){toast(`Transaction expired. Rebuilding with a fresh blockhash (${attempt+1}/3)…`);continue;}throw e;}}throw Error('Transaction expired after 3 fresh attempts. Please try again.');}
  const form=$('#launchForm');if(!form)return;form.addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();const total=[...document.querySelectorAll('.fee-input')].reduce((s,x)=>s+Number(x.value||0),0);if(total!==100){toast('Fee allocation must total 100%.');return;}if(!window.__leafConnectedAddress){toast('Connect a Solana wallet on Devnet first.');$('#walletModal')?.classList.add('open');return;}const button=form.querySelector('.launch-btn');if(button){button.disabled=true;button.innerHTML='◎ Waiting for wallet signature…';}try{const r=await mintWithRetry();form.style.display='none';$('#success')?.classList.add('show');const symbol=($('#tokenSymbol')?.value||'LEAF').toUpperCase();$('#successText').innerHTML=`<b>$${symbol}</b> SPL mint created on Solana Devnet.<br><small>Mint: ${r.mint}<br>Token account: ${r.ata}<br>Transaction: ${r.sig}</small>`;$('#txLink').href=`${EXPLORER}/tx/${r.sig}?cluster=devnet`;'#mintLink'&&($('#mintLink').href=`${EXPLORER}/address/${r.mint}?cluster=devnet`);toast(`$${symbol} created on Devnet ✓`);}catch(err){console.error(err);toast(`Mint failed: ${err?.message||err}`);}finally{if(button){button.disabled=false;button.innerHTML='Launch token <span>↗</span>';}}},true);
})();
